### PR TITLE
enhance: Use webpack 5 asset modules

### PR DESCRIPTION
**Pull request by ntucker**
https://webpack.js.org/guides/asset-modules/

### CODE REVIEW

**Comment by ljharb** [comment]
I don't know anything about webpack 5 features; i'm not planning on going anywhere near it until they fix being broken by default wrt polyfilling node stuff.

**Comment by ntucker** [comment]
As you might recall, this config turns all that back on by including aliases and process.env definition. So this is a safe way to use webpack5. 5 has other benefits like improved build times and better runtime optimizations.

**Comment by ljharb** [comment]
That sounds awesome - I'm just not able to really review it since I'm unfamiliar with webpack 5-specific features.

**Comment by ntucker** [comment]
Fair enough

**Pull request merged**
